### ISSUE TITLE
Add support for missing blocked service options

### ISSUE THREAD

**Issue by jreiml** [gmichels/terraform-provider-adguard#107]
For the latest version of Adguard (v0.107.54), the `blocked_services` property in the `adguard_client` resource does not handle [all available services](https://github.com/AdguardTeam/HostlistsRegistry/tree/main/services).

The following services are currently missing:
- 4chan
- amazon_streaming
- bluesky
- box
- discoveryplus
- dropbox
- globoplay
- kook
- nebula
- peacock_tv
- samsung_tv_plus
- slack
- yy

It might be a good idea to dynamically load the available services from the [GetBlockedServicesList](https://github.com/gmichels/adguard-client-go/blob/49cde5609320f8d6190a02d957c284597eaeab0b/blocked_services.go#L12) method.

**Comment by gmichels** [comment]
Terraform schema is supposed to be static by design, so it doesn't easily support validating the provided values against dynamic values. There are ways around it though... I will see what can be done, as it makes sense to have it dynamic.
