### ISSUE TITLE
Logging in with the provider causes: 'Could not fetch valid values from AdGuard Home'

### ISSUE THREAD

**Issue by yolanv** [gmichels/terraform-provider-adguard#120]
Hello,

My configuration is as follows:

```terraform
provider "adguard" {
  host     = "<my-internal-dns-ip>"
  username = data.aws_ssm_parameter.adguard_home_username.value
  password = data.aws_ssm_parameter.adguard_home_password.value
  timeout  = 5      # in seconds, defaults to 10
}
```

SSM parameters are deployed on AWS and contain the correct username and password (verified on console and can log in on the adguard home UI).
However, when trying to apply a resource, it gives me the following error:
```
 │ Error: Error Fetching Valid Values for Blocked Services
│ 
│   with provider["registry.opentofu.org/gmichels/adguard"],
│   on provider.tf line 5, in provider "adguard":
│    5: provider "adguard" {
│ 
│ Could not fetch valid values from AdGuard Home
```

Not sure what I am doing wrong? I am using OpenTofu version 1.8.6.

Thanks!

**Comment by gmichels** [comment]
I am missing some extra logging on those calls, to let us know what is wrong, but it's likely something in the provider configuration (username, password, scheme, etc) that is not working. I will add more logging in the coming days.

Downgrade to provider version 1.3.0 and try again, it should tell you a more descriptive error message.

**Comment by yolanv** [comment]
Authentication works on 1.3.0, thank you.
However, running into a new issue.

```terraform
 
│ Error: Error Creating DNS Rewrite Rule
│ 
│   with module.dns_records.adguard_rewrite.rewrite["dns"],
│   on dns-records/rewrite.tf line 1, in resource "adguard_rewrite" "rewrite":
│    1: resource "adguard_rewrite" "rewrite" {
│ 
│ Could not create DNS rewrite rule, unexpected error: Post
│ "https://<my-internal-dns-ip>/control/rewrite/add": tls: failed to verify
│ certificate: x509: cannot validate certificate for <my-internal-dns-ip> because
│ it doesn't contain any IP SANs

```

I tried adding `scheme="http"` to the provider but it seems to go to HTTPS.

**Comment by gmichels** [comment]
You have an untrusted (self-signed?) certificate, that's the problem.

Even if you set the scheme to `http`, your ADG instance (or some in-between proxy) is probably redirecting you to HTTPS. ADG has an option to do this redirect automatically, but I am not sure if it will make any difference for you.

At this point, you need to use a valid certificate. I will see if there is a way to introduce bypassing certificate validation.

**Comment by yolanv** [comment]
> You have an untrusted (self-signed?) certificate, that's the problem.
> 
> Even if you set the scheme to `http`, your ADG instance (or some in-between proxy) is probably redirecting you to HTTPS. ADG has an option to do this redirect automatically, but I am not sure if it will make any difference for you.
> 
> At this point, you need to use a valid certificate. I will see if there is a way to introduce bypassing certificate validation.

Makes sense. It's not a self-signed certificate. It's a certificate from Lets Encrypt generated by my reverse proxy (Caddy). Not sure if that could be an issue?

**Comment by yolanv** [comment]
Used the domain linked to the certificate instead of the IP address. Working now. Thanks for the assistance!
