### ISSUE TITLE
DNS blocklists: Disabling an existing list filter with adguard_list_filter

### ISSUE THREAD

**Issue by labbedaine** [gmichels/terraform-provider-adguard#131]
Hello.  Thank you very much for your work!

I have a fresh **_AdGuard Home_** installation and I am using Terraform to configure it.  Ideally I would avoid using the user interface for any modifications.

My goal is to disable an existing DNS blocklists but I Terraform returns an error _"Filter with URL "https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt": url already exists"._

![image](https://github.com/user-attachments/assets/41e073da-5544-4dd9-8ad1-23111675cc38)
 
```
resource "adguard_list_filter" "AdGuard_DNS_filter" {
  name      = "AdGuard DNS filter"
  url       = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt"
  enabled   = false
  whitelist = false
}
```

![image](https://github.com/user-attachments/assets/ac3c358a-7817-463c-8ef3-a7e719882c0b)

May I know if what I am trying to achieve is possible?

Thanks!

**Comment by gmichels** [comment]
If you need to manage an existing resource that was created outside of Terraform, you need to import it first to your state.

https://registry.terraform.io/providers/gmichels/adguard/latest/docs/resources/list_filter#import

After importing, you will be able to manage it as you wish.

**Comment by labbedaine** [comment]
Indeed, the import worked.

`terraform import adguard_list_filter.AdGuard_DNS_filter "1"`

**Apply**
![image](https://github.com/user-attachments/assets/81532578-3340-47f9-9b2f-2d0d4f4518a7)

I am adding an **import** step to my workflow.  Thanks!
