### ISSUE TITLE
Feature Request: Global Settings such as parental control and safe search 

### ISSUE THREAD

**Issue by gottsman** [gmichels/terraform-provider-adguard#36]
Thanks for creating the excellent terraform provider. Trying to match the exact yaml output as my current configuration. There doesn't seem to be a way to configure the safety toggles in the main settings page.

**Comment by gmichels** [comment]
@gottsman you mean these?

<img width="643" alt="image" src="https://user-images.githubusercontent.com/7144329/232662229-a24f51eb-e866-4534-82a5-28053c593f51.png">

**Comment by gottsman** [comment]
Correct. Really looking to capture the entire settings page as well as the blocked services.

http://mantua/#blocked_services
