### ISSUE TITLE
DNS rewrites not accepting all possible options

### ISSUE THREAD

**Issue by yenoromm** [gmichels/terraform-provider-adguard#60]
Adguard also supports the values 'A' and 'AAA'. These values work well if you have a wildcard such as `*.example.com` in Adguard but you want `another.exmaple.com` to be resolved upstream.

Unfortunately, this provider does not support these, here is the error I receive when I try use one of these values:

`Attribute answer must be an IP address/CIDR, MAC address, or only contain numbers, lowercase letters, and hyphens, got: A`

**Comment by gmichels** [comment]
Can you please provide the HCL you are trying?

**Comment by yenoromm** [comment]
Here is an example of where I would use an A record in conjunction with a wildcard rewrite:
```
resource "adguard_rewrite" "wildcard-example" {
  domain = "*.example.com"
  answer = "10.10.10.10"
}
```
The resource that creates the error:
```
resource "adguard_rewrite" "blog-example" {
  domain = "blog.example.com"
  answer = "A"
}
```
As you can see here this should be a valid option for Adguard:
<img width="490" alt="Screenshot 2023-07-06 at 21 43 03" src="https://github.com/gmichels/terraform-provider-adguard/assets/44349507/dd9cb870-8eab-4173-8a3a-8c1c474d2425">

**Comment by yenoromm** [comment]
Thanks maintaining a great provider!
